### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by 4U6U57** [legendddhgf/GradeMaster#3]
- [x] Set up **TravisCI** by visiting https://travis-ci.org/profile/legendddhgf
- [x] Fix **Codacy** by enabling *Post commit hook* at https://www.codacy.com/app/legendddhgf/GradeMaster/settings/integrations
- [x] Add preliminary C++ `.travis.yml`

**Comment by legendddhgf** [comment]
good job isaak...
